name: LittleBuddy
description: LittleBuddy

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.13

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  lottie: ^1.4.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  fluttertoast: ^8.2.1
  cloud_firestore: ^4.4.3
  quickalert: ^1.0.1
  provider: ^6.0.5
  flutter_svg: ^1.0.3
  gap: ^2.0.0
  # ลงตัวช่วย ของ google_maps
  google_maps_flutter: ^2.2.5
  # ส่งคำขอ Http ไป Googlemap api
  dio: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dialog_flowtter:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/nav_icons/
    - assets/stories/
    - assets/dialog_flow_auth.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

