name: LittleBuddy
description: LittleBuddy

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.13
  url_launcher: ^6.1.10
  dialogflow_flutter: ^1.0.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  lottie: ^1.4.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  fluttertoast: ^8.2.1
  cloud_firestore: ^4.4.3
  quickalert: ^1.0.1
  provider: ^6.0.5
  flutter_svg: ^1.0.3
  gap: ^2.0.0
  flutter_full_pdf_viewer: ^1.0.6

  # ลงตัวช่วย ของ google_maps
  google_maps_flutter: ^2.2.5
  # ส่งคำขอ Http ไป Googlemap api
  dio: ^5.0.1
  # หาเส้นทาง 
  google_directions_api: ^0.9.1
  # สำหรับค้นหาตำแหน่งปัจจุบันของอุปกรณ์
  geolocator: ^9.0.2
  # สำหรับใช้ GPS
  location: ^4.4.0
  permission_handler: ^10.2.0
  latlong: ^0.6.1
  firebase_storage: ^11.0.1


  bubble: ^1.1.9+1
  chips_choice: ^2.0.2
  intl:
  file_picker: ^5.2.5
  flutter_pdfview: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  dialog_flowtter:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/nav_icons/
    - assets/stories/
    - assets/dialog_flow_auth.json
    - assets/robot.jpg
    - assets/default.jpg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

